import streamlit as st


st.title("# Conclusão")

st.write("""A análise dos indicadores educacionais de 2022 a 2024 revela um panorama complexo e dinâmico nas escolas particulares e públicas. Enquanto as escolas particulares demonstram um desempenho robusto e consistente, com a eliminação da defasagem severa e a manutenção de altos índices de desenvolvimento, as escolas públicas enfrentam desafios significativos que exigem atenção e ação imediata. A leve queda em indicadores cruciais em 2024 sugere a necessidade de estratégias mais eficazes para consolidar os avanços alcançados e garantir que todos os alunos possam prosperar.""")

st.write("""A evolução das classificações dos alunos, destacando a predominância da categoria "Regular", indica que, embora muitos alunos estejam se saindo adequadamente, ainda há um considerável número que não atinge o desempenho desejado. Isso ressalta a importância de intervenções direcionadas e personalizadas que possam atender às necessidades específicas de cada aluno, especialmente aqueles em situação de defasagem. A eliminação da defasagem severa nas escolas particulares é um exemplo positivo que pode servir de modelo para as escolas públicas.""")

st.write("""Portanto, é importante que as iniciativas educacionais, como os programas da Passos Mágicos, sejam reforçadas e adaptadas para atender às realidades de cada contexto escolar. A continuidade do progresso depende de um compromisso coletivo com a melhoria da qualidade do ensino e do aprendizado, garantindo que todos os alunos tenham acesso a oportunidades equitativas e possam alcançar seu pleno potencial. Com um foco renovado em estratégias eficazes e na colaboração entre educadores, gestores e comunidades, podemos transformar o cenário educacional e construir um futuro mais promissor para todos os estudantes.""")